function write_ply_all_elements(filename,faces,verts,normals,curv)


% Create File
fileID = fopen(filename,'w');

% Plain Mesh
if nargin == 3
    
    % Insert Header
    fprintf(fileID, ...
        ['ply\n', ...
        'format ascii 1.0\n', ...
        'element vertex %u\n', ...
        'property float x\n', ...
        'property float y\n', ...
        'property float z\n', ...
        'element face %u\n', ...
        'property list uint int vertex_indices\n', ...
        'end_header\n'], ...
        length(verts),length(faces));

    % Insert Colored Vertices
    for i=1:length(verts)
        fprintf(fileID, ...
            ['%0.6f ', ...
            '%0.6f ', ...
            '%0.6f\n'], ...
            verts(i,1),verts(i,2),verts(i,3));
    end

    % Insert Faces
    dlmwrite(filename,[size(faces,2)*ones(length(faces),1),faces-1],'-append','delimiter',' ','precision',10);

% Mesh w/ normal vectors
elseif nargin == 4
    
    % Insert Header
    fprintf(fileID, ...
        ['ply\n', ...
        'format ascii 1.0\n', ...
        'element vertex %u\n', ...
        'property float x\n', ...
        'property float y\n', ...
        'property float z\n', ...
        'property float nx\n', ...
        'property float ny\n', ...
        'property float nz\n', ...
        'element face %u\n', ...
        'property list uint int vertex_indices\n', ...
        'end_header\n'], ...
        length(verts),length(faces));

    % Insert Colored Vertices
    for i=1:length(verts)
    fprintf(fileID, ...
        ['%0.6f ', ...
        '%0.6f ', ...
        '%0.6f ', ...
        '%0.6f ', ...
        '%0.6f ', ...
        '%0.6f\n'], ...
        verts(i,1),verts(i,2),verts(i,3),normals(i,1),normals(i,2),normals(i,3));
    end

    % Insert Faces
    dlmwrite(filename,[size(faces,2)*ones(length(faces),1),faces-1],'-append','delimiter',' ','precision',10);

   
% Mesh w/ normals and curvature    
elseif nargin == 5
    
    % Insert Header
    fprintf(fileID, ...
        ['ply\n', ...
        'format ascii 1.0\n', ...
        'element vertex %u\n', ...
        'property float x\n', ...
        'property float y\n', ...
        'property float z\n', ...
        'property float nx\n', ...
        'property float ny\n', ...
        'property float nz\n', ...
        'property float quality\n', ...
        'element face %u\n', ...
        'property list uint int vertex_indices\n', ...
        'end_header\n'], ...
        length(verts),length(faces));

    % Insert Colored Vertices
    for i=1:length(verts)
    fprintf(fileID, ...
        ['%0.6f ', ...
        '%0.6f ', ...
        '%0.6f ', ...
        '%0.6f ', ...
        '%0.6f ', ...
        '%0.6f ', ...
        '%0.6f\n'], ...
        verts(i,1),verts(i,2),verts(i,3),normals(i,1),normals(i,2),normals(i,3),curv(i));
    end

    % Insert Faces
    dlmwrite(filename,[size(faces,2)*ones(length(faces),1),faces-1],'-append','delimiter',' ','precision',10);

else
    error('write_ply_all_elements:: Incorrect Nargin. Expected <= 5, Recieved %u', nargin)
end
    
    
    
end


